---
version: '1.0.{build}'

os: Visual Studio 2015

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - nuget restore

build:
  verbosity: minimal
  project: LibSass.NET.sln

test_script:
  - packages\xunit.runner.console.2.1.0\tools\xunit.console tests\bin\%configuration%\LibSass.NET.Tests.dll

on_success:
  - 7z a libsass-net.zip .
  - ps: Push-AppveyorArtifact libsass-net.zip
